<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "turnjs4typo3"
 *
 * Auto generated by Extension Builder 2020-05-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TurnJs4Typo3',
    'description' => 'Manages Documents and displays them with turnJs',
    'category' => 'plugin',
    'author' => 'Tobias Eichelbrönner',
    'author_email' => 'newsletter@lygie.de',
    'state' => 'beta',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.3',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
